name: cypress tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/hithub-action@v2
        with:
          build: npm run build
          start: npm start
          browser: chrome
